tools:
  trim: trimmomatic
#  trim: trimgalore
  map: hisat2
#  map: STAR
  expr: stringtie
#  expr: HTseq

samples:
  Exp_2_3:
    - raw_data/samples/Exp_2_3_1.fastq.gz
    - raw_data/samples/Exp_2_3_2.fastq.gz
  Neg_1_2:
    - raw_data/samples/Neg_1_2_1.fastq.gz
    - raw_data/samples/Neg_1_2_2.fastq.gz
pairedreads:
  - 1
  - 2
genome:
  genome_name: WBcel235
  genome_file: raw_data/references/WBcel235.fa
  annotation_file: raw_data/references/WBcel235_GCF_000002985.6.gtf
  transcriptome: raw_data/references/WBcel235_transcriptome_GCF_000002985.6.fa
  annotation_file2: raw_data/references/WBcel235.gtf
adapters: raw_data/references/TruSeq3-PE-2.fa
trimming:
  adaptlen: 5
  minlen: 36
  quality: 15